#!/usr/bin/env python3
"""Build image_input_map JSON for run_seedance_test.py from keyframe manifest."""

from __future__ import annotations

import argparse
import base64
import json
import mimetypes
import sys
from pathlib import Path
from typing import Any


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def encode_local_image_as_data_uri(path: Path) -> str:
    raw = path.read_bytes()
    guessed = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
    b64 = base64.b64encode(raw).decode("ascii")
    return f"data:{guessed};base64,{b64}"


def first_non_empty(values: list[str]) -> str:
    for v in values:
        if v.strip():
            return v.strip()
    return ""


def resolve_ref(
    value: str,
    project_root: Path,
    allow_data_uri_from_local: bool,
) -> str:
    v = value.strip()
    if not v:
        return ""
    if v.startswith("http://") or v.startswith("https://") or v.startswith("data:"):
        return v
    p = Path(v).expanduser()
    if not p.is_absolute():
        p = (project_root / p).resolve()
    if p.exists():
        if allow_data_uri_from_local:
            return encode_local_image_as_data_uri(p)
        return str(p)
    return v


def extract_phase_ref(
    phase_meta: dict[str, Any],
    project_root: Path,
    allow_data_uri_from_local: bool,
) -> str:
    candidates = [
        str(phase_meta.get("output_url", "")).strip(),
        str(phase_meta.get("output_data_uri", "")).strip(),
        str(phase_meta.get("output_file", "")).strip(),
    ]
    return resolve_ref(
        value=first_non_empty(candidates),
        project_root=project_root,
        allow_data_uri_from_local=allow_data_uri_from_local,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build image_input_map JSON from keyframe_manifest.json."
    )
    parser.add_argument(
        "--manifest",
        required=True,
        help="Path to keyframe_manifest.json generated by generate_keyframes_atlas_i2i.py",
    )
    parser.add_argument(
        "--out",
        required=True,
        help="Output JSON path for image_input_map.",
    )
    parser.add_argument(
        "--allow-data-uri-from-local",
        action="store_true",
        help="If output_file is local path and no URL exists, convert local image to data URI.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail when any selected shot is missing required refs.",
    )
    parser.add_argument(
        "--allow-missing-last-image",
        action="store_true",
        help="Allow start-only keyframe manifests and omit last_image when end refs are missing.",
    )
    parser.add_argument(
        "--shots",
        default="",
        help="Optional comma-separated shot ids to export. Empty means all in manifest.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest_path = Path(args.manifest).expanduser().resolve()
    out_path = Path(args.out).expanduser().resolve()
    project_root = manifest_path.parents[2] if len(manifest_path.parents) >= 3 else Path.cwd()

    if not manifest_path.exists():
        print(f"[ERROR] manifest not found: {manifest_path}", file=sys.stderr)
        return 1

    data = read_json(manifest_path)
    shots_result = data.get("shots_result", {})
    if not isinstance(shots_result, dict):
        print("[ERROR] manifest format invalid: shots_result missing or not object", file=sys.stderr)
        return 1

    selected_shots: list[str]
    if args.shots.strip():
        selected_shots = [s.strip().upper() for s in args.shots.split(",") if s.strip()]
    else:
        selected_shots = sorted([str(k).strip().upper() for k in shots_result.keys() if str(k).strip()])

    image_input_map: dict[str, dict[str, str]] = {}
    errors: list[str] = []

    for shot_id in selected_shots:
        shot_meta = shots_result.get(shot_id, {})
        if not isinstance(shot_meta, dict):
            errors.append(f"{shot_id}: shot meta missing")
            continue

        start_meta = shot_meta.get("start", {})
        end_meta = shot_meta.get("end", {})
        if not isinstance(start_meta, dict):
            errors.append(f"{shot_id}: start phase meta missing")
            continue
        if not isinstance(end_meta, dict):
            end_meta = {}

        image_ref = extract_phase_ref(
            phase_meta=start_meta,
            project_root=project_root,
            allow_data_uri_from_local=bool(args.allow_data_uri_from_local),
        )
        last_image_ref = extract_phase_ref(
            phase_meta=end_meta,
            project_root=project_root,
            allow_data_uri_from_local=bool(args.allow_data_uri_from_local),
        )

        if not image_ref:
            errors.append(f"{shot_id}: missing image")
            continue
        if not last_image_ref and not args.allow_missing_last_image:
            errors.append(f"{shot_id}: missing last_image")
            continue

        entry = {"image": image_ref}
        if last_image_ref:
            entry["last_image"] = last_image_ref

        image_input_map[shot_id] = entry

    out_path.parent.mkdir(parents=True, exist_ok=True)
    write_json(out_path, image_input_map)

    print(f"[INFO] image_input_map written: {out_path}")
    print(f"[INFO] entries: {len(image_input_map)}")
    if errors:
        print("[WARN] issues:")
        for err in errors:
            print(f"  - {err}")
        if args.strict:
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
